apiVersion: deploycontrol.k8s.io/v1alpha1
kind: DeployDaemon
metadata:
  name: test-deploydaemon
spec:
  tenant: demo
  environment: qa
  envtype: auth
  component: ts-app
  scheduler: 1m
  image: nginx:latest
  version: 9.0.1.2
  instance: 1
  expose: online
  configRef: demoqaauth
  secrets:
    - paramName: VAULT_TOKEN
      secretName: demoqaauth_vaulttoken

